version: "3.7"
services:
  mysql:
    build:
      context: .
      dockerfile: .docker/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
  webserver:
    build:
      context: .
      dockerfile: .docker/php
    depends_on:
      - mysql
    volumes:
      - "./:/var/www/html/"
    ports:
      - "80:80"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.4
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
